name = "llmtext"
main = "main.ts"
compatibility_date = "2025-02-05"
dev.port = 3000
kv_namespaces = [
  { binding = "CACHED_URLS", id = "3c8ff80a2d2147ff9bd16b48cd9bedef" }
]
routes = [
  { pattern = "llmtext.com", custom_domain = true },
  { pattern = "www.llmtext.com", custom_domain = true }
]
assets.directory = "./public"
